package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class Blacklist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.id
     * 
     */
    private Long id;

    /**
     * 客户id -- blacklist.customer_id
     * 
     */
    private Long customerId;

    /**
     * 申请类型 -- blacklist.application_type
     * 
     */
    private String applicationType;

    /**
     * 申请时间 -- blacklist.create_time
     * 
     */
    private Date createTime;

    /**
     * 申请人 -- blacklist.create_name
     * 
     */
    private String createName;

    /**
     * 申请原因 -- blacklist.create_reason
     * 
     */
    private String createReason;

    /**
     * 审批人 -- blacklist.approver
     * 
     */
    private String approver;

    /**
     * 审批时间 -- blacklist.approvel_time
     * 
     */
    private Date approvelTime;

    /**
     * 1,黑名单 2,正常 -- blacklist.status
     * 
     */
    private Integer status;

    /**
     * 加入黑名单原因 -- blacklist.join_reason
     * 
     */
    private String joinReason;

    /**
     * 详细原因 -- blacklist.memo
     * 
     */
    private String memo;

    /**
     * 流程id -- blacklist.process_id
     * 
     */
    private Long processId;

    /**
     * 1,通过 2,未通过 -- blacklist.approvl_status
     * 
     */
    private Integer approvlStatus;

    /**
     * 图片路径 -- blacklist.file_path
     * 
     */
    private String filePath;

    /**
     * 审批意见 -- blacklist.approvel_opinion
     * 
     */
    private String approvelOpinion;

    /**
     * blacklist表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 blacklist.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 blacklist.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 blacklist.customer_id的get方法 
     * 
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * 数据字段 blacklist.customer_id的set方法
     * 
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * 数据字段 blacklist.application_type的get方法 
     * 
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * 数据字段 blacklist.application_type的set方法
     * 
     */
    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType == null ? null : applicationType.trim();
    }

    /**
     * 数据字段 blacklist.create_time的get方法 
     * 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 blacklist.create_time的set方法
     * 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 blacklist.create_name的get方法 
     * 
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * 数据字段 blacklist.create_name的set方法
     * 
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * 数据字段 blacklist.create_reason的get方法 
     * 
     */
    public String getCreateReason() {
        return createReason;
    }

    /**
     * 数据字段 blacklist.create_reason的set方法
     * 
     */
    public void setCreateReason(String createReason) {
        this.createReason = createReason == null ? null : createReason.trim();
    }

    /**
     * 数据字段 blacklist.approver的get方法 
     * 
     */
    public String getApprover() {
        return approver;
    }

    /**
     * 数据字段 blacklist.approver的set方法
     * 
     */
    public void setApprover(String approver) {
        this.approver = approver == null ? null : approver.trim();
    }

    /**
     * 数据字段 blacklist.approvel_time的get方法 
     * 
     */
    public Date getApprovelTime() {
        return approvelTime;
    }

    /**
     * 数据字段 blacklist.approvel_time的set方法
     * 
     */
    public void setApprovelTime(Date approvelTime) {
        this.approvelTime = approvelTime;
    }

    /**
     * 数据字段 blacklist.status的get方法 
     * 
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 数据字段 blacklist.status的set方法
     * 
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 数据字段 blacklist.join_reason的get方法 
     * 
     */
    public String getJoinReason() {
        return joinReason;
    }

    /**
     * 数据字段 blacklist.join_reason的set方法
     * 
     */
    public void setJoinReason(String joinReason) {
        this.joinReason = joinReason == null ? null : joinReason.trim();
    }

    /**
     * 数据字段 blacklist.memo的get方法 
     * 
     */
    public String getMemo() {
        return memo;
    }

    /**
     * 数据字段 blacklist.memo的set方法
     * 
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * 数据字段 blacklist.process_id的get方法 
     * 
     */
    public Long getProcessId() {
        return processId;
    }

    /**
     * 数据字段 blacklist.process_id的set方法
     * 
     */
    public void setProcessId(Long processId) {
        this.processId = processId;
    }

    /**
     * 数据字段 blacklist.approvl_status的get方法 
     * 
     */
    public Integer getApprovlStatus() {
        return approvlStatus;
    }

    /**
     * 数据字段 blacklist.approvl_status的set方法
     * 
     */
    public void setApprovlStatus(Integer approvlStatus) {
        this.approvlStatus = approvlStatus;
    }

    /**
     * 数据字段 blacklist.file_path的get方法 
     * 
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * 数据字段 blacklist.file_path的set方法
     * 
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * 数据字段 blacklist.approvel_opinion的get方法 
     * 
     */
    public String getApprovelOpinion() {
        return approvelOpinion;
    }

    /**
     * 数据字段 blacklist.approvel_opinion的set方法
     * 
     */
    public void setApprovelOpinion(String approvelOpinion) {
        this.approvelOpinion = approvelOpinion == null ? null : approvelOpinion.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}