package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class BusinessInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.id
     * 
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.create_time
     * 
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.update_time
     * 
     */
    private Date updateTime;

    /**
     * 产品模块ID（引用business_module.id） -- business_info.business_module_id
     * 
     */
    private Long businessModuleId;

    /**
     * 商家名称 -- business_info.business_name
     * 
     */
    private String businessName;

    /**
     * 商家编号 -- business_info.business_no
     * 
     */
    private String businessNo;

    /**
     * 收款人姓名 -- business_info.payee_name
     * 
     */
    private String payeeName;

    /**
     * 收款人账号 -- business_info.payee_account
     * 
     */
    private String payeeAccount;

    /**
     * 开户行类型（
1-中国银行、
2-建设银行、
3-平安银行、
4-农业银行、
等，
源于数据字典） -- business_info.bank_type
     * 
     */
    private String bankType;

    /**
     * 还款方式（
1-等额平息、
2-等额本息，
源于数据字典） -- business_info.repayment_method
     * 
     */
    private String repaymentMethod;

    /**
     * 月利率（单位：千分比） -- business_info.monthly_rate
     * 
     */
    private BigDecimal monthlyRate;

    /**
     * 1-启用、2-禁用 -- business_info.enable
     * 
     */
    private String enable;

    /**
     * 记录状态（1-正常、0-删除） -- business_info.status
     * 
     */
    private Integer status;

    /**
     * 支行 -- business_info.branch
     * 
     */
    private String branch;

    /**
     * business_info表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 business_info.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 business_info.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 business_info.create_time的get方法 
     * 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 business_info.create_time的set方法
     * 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 business_info.update_time的get方法 
     * 
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 business_info.update_time的set方法
     * 
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 business_info.business_module_id的get方法 
     * 
     */
    public Long getBusinessModuleId() {
        return businessModuleId;
    }

    /**
     * 数据字段 business_info.business_module_id的set方法
     * 
     */
    public void setBusinessModuleId(Long businessModuleId) {
        this.businessModuleId = businessModuleId;
    }

    /**
     * 数据字段 business_info.business_name的get方法 
     * 
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * 数据字段 business_info.business_name的set方法
     * 
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * 数据字段 business_info.business_no的get方法 
     * 
     */
    public String getBusinessNo() {
        return businessNo;
    }

    /**
     * 数据字段 business_info.business_no的set方法
     * 
     */
    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo == null ? null : businessNo.trim();
    }

    /**
     * 数据字段 business_info.payee_name的get方法 
     * 
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * 数据字段 business_info.payee_name的set方法
     * 
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * 数据字段 business_info.payee_account的get方法 
     * 
     */
    public String getPayeeAccount() {
        return payeeAccount;
    }

    /**
     * 数据字段 business_info.payee_account的set方法
     * 
     */
    public void setPayeeAccount(String payeeAccount) {
        this.payeeAccount = payeeAccount == null ? null : payeeAccount.trim();
    }

    /**
     * 数据字段 business_info.bank_type的get方法 
     * 
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * 数据字段 business_info.bank_type的set方法
     * 
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * 数据字段 business_info.repayment_method的get方法 
     * 
     */
    public String getRepaymentMethod() {
        return repaymentMethod;
    }

    /**
     * 数据字段 business_info.repayment_method的set方法
     * 
     */
    public void setRepaymentMethod(String repaymentMethod) {
        this.repaymentMethod = repaymentMethod == null ? null : repaymentMethod.trim();
    }

    /**
     * 数据字段 business_info.monthly_rate的get方法 
     * 
     */
    public BigDecimal getMonthlyRate() {
        return monthlyRate;
    }

    /**
     * 数据字段 business_info.monthly_rate的set方法
     * 
     */
    public void setMonthlyRate(BigDecimal monthlyRate) {
        this.monthlyRate = monthlyRate;
    }

    /**
     * 数据字段 business_info.enable的get方法 
     * 
     */
    public String getEnable() {
        return enable;
    }

    /**
     * 数据字段 business_info.enable的set方法
     * 
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * 数据字段 business_info.status的get方法 
     * 
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 数据字段 business_info.status的set方法
     * 
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 数据字段 business_info.branch的get方法 
     * 
     */
    public String getBranch() {
        return branch;
    }

    /**
     * 数据字段 business_info.branch的set方法
     * 
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}