package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class ContractNoRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_no_rule.id
     * 
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_no_rule.created_time
     * 
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_no_rule.updated_time
     * 
     */
    private Date updatedTime;

    /**
     * 排序号 -- contract_no_rule.sort_no
     * 
     */
    private String sortNo;

    /**
     * 规则对象类型：授信合同、借款合同、担保合同 -- contract_no_rule.contract_type
     * 
     */
    private Integer contractType;

    /**
     * 编码依据：如自定义规则、固定规则等 -- contract_no_rule.rule_gist
     * 
     */
    private Integer ruleGist;

    /**
     * 编码规则名称 -- contract_no_rule.rule_name
     * 
     */
    private String ruleName;

    /**
     * 规则说明 -- contract_no_rule.rule_memo
     * 
     */
    private String ruleMemo;

    /**
     * 具体规则 -- contract_no_rule.rule
     * 
     */
    private String rule;

    /**
     * 时间参数规则：不重置、按年递增（后面的流水号每年度将从1重新开始）、按月递增（后面的流水号每月将从1重新开始）、按日递增（后面的流水号每天将从1重新开始） -- contract_no_rule.time_param_rule
     * 
     */
    private Integer timeParamRule;

    /**
     * 合同参数规则，下拉可选，目前只有“无”这个选项 -- contract_no_rule.contract_param_rule
     * 
     */
    private Integer contractParamRule;

    /**
     * 0-停用，1-启用 -- contract_no_rule.status
     * 
     */
    private Integer status;

    /**
     * contract_no_rule表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 contract_no_rule.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 contract_no_rule.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 contract_no_rule.created_time的get方法 
     * 
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 数据字段 contract_no_rule.created_time的set方法
     * 
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 数据字段 contract_no_rule.updated_time的get方法 
     * 
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 数据字段 contract_no_rule.updated_time的set方法
     * 
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * 数据字段 contract_no_rule.sort_no的get方法 
     * 
     */
    public String getSortNo() {
        return sortNo;
    }

    /**
     * 数据字段 contract_no_rule.sort_no的set方法
     * 
     */
    public void setSortNo(String sortNo) {
        this.sortNo = sortNo == null ? null : sortNo.trim();
    }

    /**
     * 数据字段 contract_no_rule.contract_type的get方法 
     * 
     */
    public Integer getContractType() {
        return contractType;
    }

    /**
     * 数据字段 contract_no_rule.contract_type的set方法
     * 
     */
    public void setContractType(Integer contractType) {
        this.contractType = contractType;
    }

    /**
     * 数据字段 contract_no_rule.rule_gist的get方法 
     * 
     */
    public Integer getRuleGist() {
        return ruleGist;
    }

    /**
     * 数据字段 contract_no_rule.rule_gist的set方法
     * 
     */
    public void setRuleGist(Integer ruleGist) {
        this.ruleGist = ruleGist;
    }

    /**
     * 数据字段 contract_no_rule.rule_name的get方法 
     * 
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * 数据字段 contract_no_rule.rule_name的set方法
     * 
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * 数据字段 contract_no_rule.rule_memo的get方法 
     * 
     */
    public String getRuleMemo() {
        return ruleMemo;
    }

    /**
     * 数据字段 contract_no_rule.rule_memo的set方法
     * 
     */
    public void setRuleMemo(String ruleMemo) {
        this.ruleMemo = ruleMemo == null ? null : ruleMemo.trim();
    }

    /**
     * 数据字段 contract_no_rule.rule的get方法 
     * 
     */
    public String getRule() {
        return rule;
    }

    /**
     * 数据字段 contract_no_rule.rule的set方法
     * 
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * 数据字段 contract_no_rule.time_param_rule的get方法 
     * 
     */
    public Integer getTimeParamRule() {
        return timeParamRule;
    }

    /**
     * 数据字段 contract_no_rule.time_param_rule的set方法
     * 
     */
    public void setTimeParamRule(Integer timeParamRule) {
        this.timeParamRule = timeParamRule;
    }

    /**
     * 数据字段 contract_no_rule.contract_param_rule的get方法 
     * 
     */
    public Integer getContractParamRule() {
        return contractParamRule;
    }

    /**
     * 数据字段 contract_no_rule.contract_param_rule的set方法
     * 
     */
    public void setContractParamRule(Integer contractParamRule) {
        this.contractParamRule = contractParamRule;
    }

    /**
     * 数据字段 contract_no_rule.status的get方法 
     * 
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 数据字段 contract_no_rule.status的set方法
     * 
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}