package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class CustomerAccount implements Serializable {
    /**
     * 自增长主键 -- customer_account.id
     * 
     */
    private Long id;

    /**
     * 创建时间 -- customer_account.created_time
     * 
     */
    private Date createdTime;

    /**
     * 修改时间 -- customer_account.updated_time
     * 
     */
    private Date updatedTime;

    /**
     * 客户编号，关联customer_info.id -- customer_account.customer_id
     * 
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_account.bank_code
     * 
     */
    private String bankCode;

    /**
     * 开户银行 -- customer_account.bank_name
     * 
     */
    private String bankName;

    /**
     * 银行支行名称 -- customer_account.branch_bank_name
     * 
     */
    private String branchBankName;

    /**
     * 银行卡号 -- customer_account.bank_card_no
     * 
     */
    private String bankCardNo;

    /**
     * 账户户名 -- customer_account.account_name
     * 
     */
    private String accountName;

    /**
     * 账户类型 -- customer_account.account_type
     * 
     */
    private String accountType;

    /**
     * 商户号 -- customer_account.merchant_no
     * 
     */
    private String merchantNo;

    /**
     * 登陆号 -- customer_account.login_name
     * 
     */
    private String loginName;

    /**
     * 是否默认账户 -- customer_account.is_default_account
     * 
     */
    private String isDefaultAccount;

    /**
     * 操作标志：delete=删除，update=修改，add=新增 -- customer_account.status
     * 
     */
    private String status;

    /**
     * 银行预留手机号码 -- customer_account.mobile
     * 
     */
    private String mobile;

    /**
     * customer_account表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 customer_account.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 customer_account.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 customer_account.created_time的get方法 
     * 
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 数据字段 customer_account.created_time的set方法
     * 
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 数据字段 customer_account.updated_time的get方法 
     * 
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 数据字段 customer_account.updated_time的set方法
     * 
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * 数据字段 customer_account.customer_id的get方法 
     * 
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * 数据字段 customer_account.customer_id的set方法
     * 
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * 数据字段 customer_account.bank_code的get方法 
     * 
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * 数据字段 customer_account.bank_code的set方法
     * 
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * 数据字段 customer_account.bank_name的get方法 
     * 
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * 数据字段 customer_account.bank_name的set方法
     * 
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * 数据字段 customer_account.branch_bank_name的get方法 
     * 
     */
    public String getBranchBankName() {
        return branchBankName;
    }

    /**
     * 数据字段 customer_account.branch_bank_name的set方法
     * 
     */
    public void setBranchBankName(String branchBankName) {
        this.branchBankName = branchBankName == null ? null : branchBankName.trim();
    }

    /**
     * 数据字段 customer_account.bank_card_no的get方法 
     * 
     */
    public String getBankCardNo() {
        return bankCardNo;
    }

    /**
     * 数据字段 customer_account.bank_card_no的set方法
     * 
     */
    public void setBankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo == null ? null : bankCardNo.trim();
    }

    /**
     * 数据字段 customer_account.account_name的get方法 
     * 
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * 数据字段 customer_account.account_name的set方法
     * 
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * 数据字段 customer_account.account_type的get方法 
     * 
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * 数据字段 customer_account.account_type的set方法
     * 
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * 数据字段 customer_account.merchant_no的get方法 
     * 
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * 数据字段 customer_account.merchant_no的set方法
     * 
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * 数据字段 customer_account.login_name的get方法 
     * 
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 数据字段 customer_account.login_name的set方法
     * 
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * 数据字段 customer_account.is_default_account的get方法 
     * 
     */
    public String getIsDefaultAccount() {
        return isDefaultAccount;
    }

    /**
     * 数据字段 customer_account.is_default_account的set方法
     * 
     */
    public void setIsDefaultAccount(String isDefaultAccount) {
        this.isDefaultAccount = isDefaultAccount == null ? null : isDefaultAccount.trim();
    }

    /**
     * 数据字段 customer_account.status的get方法 
     * 
     */
    public String getStatus() {
        return status;
    }

    /**
     * 数据字段 customer_account.status的set方法
     * 
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 数据字段 customer_account.mobile的get方法 
     * 
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 数据字段 customer_account.mobile的set方法
     * 
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}