package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class CustomerInfo implements Serializable {
    /**
     * 客户id（主键） -- customer_info.id
     * 
     */
    private Long id;

    /**
     * 客户编号 -- customer_info.customer_no
     * 
     */
    private String customerNo;

    /**
     * 客户名称 -- customer_info.customer_name
     * 
     */
    private String customerName;

    /**
     * 客户类别：1 个人 2 企业 -- customer_info.customer_class
     * 
     */
    private String customerClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.created_time
     * 
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.updated_time
     * 
     */
    private Date updatedTime;

    /**
     * 客户经理名称 -- customer_info.customer_manager_name
     * 
     */
    private String customerManagerName;

    /**
     * 客户类型：财务客户、其他客户、担保客户、贷款客户、关联客户 -- customer_info.customer_type
     * 
     */
    private String customerType;

    /**
     * 客户来源： 其它 广告获得 自己上门 推荐 -- customer_info.customer_source
     * 
     */
    private String customerSource;

    /**
     * 客户经理ID -- customer_info.user_id
     * 
     */
    private Long userId;

    /**
     * 部门 -- customer_info.department_id
     * 
     */
    private String departmentId;

    /**
     * 客户经理所在机构ID -- customer_info.org_id
     * 
     */
    private Long orgId;

    /**
     * 客户经理所在用户组ID -- customer_info.group_id
     * 
     */
    private Long groupId;

    /**
     * 是否储备客户：0-否；1-是 -- customer_info.reserve_customer
     * 
     */
    private String reserveCustomer;

    /**
     * 客户状态：0-已删除；1-正常 -- customer_info.customer_status
     * 
     */
    private String customerStatus;

    /**
     * 证件类型：身份证、护照、军人证、社保卡、居住证、营业执照 -- customer_info.cert_type
     * 
     */
    private String certType;

    /**
     * 证件号码（企业的是营业执照） -- customer_info.cert_no
     * 
     */
    private String certNo;

    /**
     * 审批日期 -- customer_info.approved_date
     * 
     */
    private Date approvedDate;

    /**
     * 审批流程实例ID -- customer_info.approval_process_id
     * 
     */
    private String approvalProcessId;

    /**
     * 审批流程状态(1:未修改，2：修改审批中，3：修改完成) -- customer_info.approval_status
     * 
     */
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.approval_status_time
     * 
     */
    private String approvalStatusTime;

    /**
     * 审批状态变更相关的消息 -- customer_info.approval_status_msg
     * 
     */
    private String approvalStatusMsg;

    /**
     * 行政区划-省 -- customer_info.district_province
     * 
     */
    private String districtProvince;

    /**
     * 行政区划-市 -- customer_info.district_city
     * 
     */
    private String districtCity;

    /**
     * 行政区划-县 -- customer_info.district_county
     * 
     */
    private String districtCounty;

    /**
     * 对象明细：城镇个体工商、农村个体工商、城镇居民、农民 -- customer_info.identity_detail
     * 
     */
    private String identityDetail;

    /**
     * 联系电话（个人为手机号码1，企业为联系电话） -- customer_info.contact_phone
     * 
     */
    private String contactPhone;

    /**
     * 注册地址（户籍地址）-省 -- customer_info.register_address_province
     * 
     */
    private String registerAddressProvince;

    /**
     * 注册地址（户籍地址）-市 -- customer_info.register_address_city
     * 
     */
    private String registerAddressCity;

    /**
     * 注册地址（户籍地址）-县（区） -- customer_info.register_address_country
     * 
     */
    private String registerAddressCountry;

    /**
     * 注册地址（户籍地址）-详细地址 -- customer_info.register_address_detail
     * 
     */
    private String registerAddressDetail;

    /**
     * 居住地址(通讯地址)-省 -- customer_info.live_address_province
     * 
     */
    private String liveAddressProvince;

    /**
     * 居住地址(通讯地址)-市 -- customer_info.live_address_city
     * 
     */
    private String liveAddressCity;

    /**
     * 居住地址(通讯地址)-县（区） -- customer_info.live_address_country
     * 
     */
    private String liveAddressCountry;

    /**
     * 居住地址(通讯地址)-详细地址 -- customer_info.live_address_detail
     * 
     */
    private String liveAddressDetail;

    /**
     * 客户评级 -- customer_info.customer_grade
     * 
     */
    private String customerGrade;

    /**
     * 客户在用友财务系统中的代号 简称客商编码  -- customer_info.financial_code
     * 
     */
    private String financialCode;

    /**
     * 第一联系人姓名 -- customer_info.first_contact_name
     * 
     */
    private String firstContactName;

    /**
     * 第一联系联系号码 -- customer_info.first_contact_phone
     * 
     */
    private String firstContactPhone;

    /**
     * 客户所属行业 -- customer_info.customer_industry
     * 
     */
    private String customerIndustry;

    /**
     * 老客户类型0：不是老客户1：手机老客户2：宽带老客户3：全是 -- customer_info.frequent_customer
     * 
     */
    private String frequentCustomer;

    /**
     * 是否为黑名单 1-黑名单 2- 正常 -- customer_info.isBlack
     * 
     */
    private Integer isblack;

    /**
     * customer_info表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 customer_info.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 customer_info.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 customer_info.customer_no的get方法 
     * 
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * 数据字段 customer_info.customer_no的set方法
     * 
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo == null ? null : customerNo.trim();
    }

    /**
     * 数据字段 customer_info.customer_name的get方法 
     * 
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * 数据字段 customer_info.customer_name的set方法
     * 
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * 数据字段 customer_info.customer_class的get方法 
     * 
     */
    public String getCustomerClass() {
        return customerClass;
    }

    /**
     * 数据字段 customer_info.customer_class的set方法
     * 
     */
    public void setCustomerClass(String customerClass) {
        this.customerClass = customerClass == null ? null : customerClass.trim();
    }

    /**
     * 数据字段 customer_info.created_time的get方法 
     * 
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 数据字段 customer_info.created_time的set方法
     * 
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 数据字段 customer_info.updated_time的get方法 
     * 
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 数据字段 customer_info.updated_time的set方法
     * 
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * 数据字段 customer_info.customer_manager_name的get方法 
     * 
     */
    public String getCustomerManagerName() {
        return customerManagerName;
    }

    /**
     * 数据字段 customer_info.customer_manager_name的set方法
     * 
     */
    public void setCustomerManagerName(String customerManagerName) {
        this.customerManagerName = customerManagerName == null ? null : customerManagerName.trim();
    }

    /**
     * 数据字段 customer_info.customer_type的get方法 
     * 
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * 数据字段 customer_info.customer_type的set方法
     * 
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * 数据字段 customer_info.customer_source的get方法 
     * 
     */
    public String getCustomerSource() {
        return customerSource;
    }

    /**
     * 数据字段 customer_info.customer_source的set方法
     * 
     */
    public void setCustomerSource(String customerSource) {
        this.customerSource = customerSource == null ? null : customerSource.trim();
    }

    /**
     * 数据字段 customer_info.user_id的get方法 
     * 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 数据字段 customer_info.user_id的set方法
     * 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 数据字段 customer_info.department_id的get方法 
     * 
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * 数据字段 customer_info.department_id的set方法
     * 
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * 数据字段 customer_info.org_id的get方法 
     * 
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 数据字段 customer_info.org_id的set方法
     * 
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 数据字段 customer_info.group_id的get方法 
     * 
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * 数据字段 customer_info.group_id的set方法
     * 
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 数据字段 customer_info.reserve_customer的get方法 
     * 
     */
    public String getReserveCustomer() {
        return reserveCustomer;
    }

    /**
     * 数据字段 customer_info.reserve_customer的set方法
     * 
     */
    public void setReserveCustomer(String reserveCustomer) {
        this.reserveCustomer = reserveCustomer == null ? null : reserveCustomer.trim();
    }

    /**
     * 数据字段 customer_info.customer_status的get方法 
     * 
     */
    public String getCustomerStatus() {
        return customerStatus;
    }

    /**
     * 数据字段 customer_info.customer_status的set方法
     * 
     */
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus == null ? null : customerStatus.trim();
    }

    /**
     * 数据字段 customer_info.cert_type的get方法 
     * 
     */
    public String getCertType() {
        return certType;
    }

    /**
     * 数据字段 customer_info.cert_type的set方法
     * 
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * 数据字段 customer_info.cert_no的get方法 
     * 
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * 数据字段 customer_info.cert_no的set方法
     * 
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * 数据字段 customer_info.approved_date的get方法 
     * 
     */
    public Date getApprovedDate() {
        return approvedDate;
    }

    /**
     * 数据字段 customer_info.approved_date的set方法
     * 
     */
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    /**
     * 数据字段 customer_info.approval_process_id的get方法 
     * 
     */
    public String getApprovalProcessId() {
        return approvalProcessId;
    }

    /**
     * 数据字段 customer_info.approval_process_id的set方法
     * 
     */
    public void setApprovalProcessId(String approvalProcessId) {
        this.approvalProcessId = approvalProcessId == null ? null : approvalProcessId.trim();
    }

    /**
     * 数据字段 customer_info.approval_status的get方法 
     * 
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * 数据字段 customer_info.approval_status的set方法
     * 
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    /**
     * 数据字段 customer_info.approval_status_time的get方法 
     * 
     */
    public String getApprovalStatusTime() {
        return approvalStatusTime;
    }

    /**
     * 数据字段 customer_info.approval_status_time的set方法
     * 
     */
    public void setApprovalStatusTime(String approvalStatusTime) {
        this.approvalStatusTime = approvalStatusTime == null ? null : approvalStatusTime.trim();
    }

    /**
     * 数据字段 customer_info.approval_status_msg的get方法 
     * 
     */
    public String getApprovalStatusMsg() {
        return approvalStatusMsg;
    }

    /**
     * 数据字段 customer_info.approval_status_msg的set方法
     * 
     */
    public void setApprovalStatusMsg(String approvalStatusMsg) {
        this.approvalStatusMsg = approvalStatusMsg == null ? null : approvalStatusMsg.trim();
    }

    /**
     * 数据字段 customer_info.district_province的get方法 
     * 
     */
    public String getDistrictProvince() {
        return districtProvince;
    }

    /**
     * 数据字段 customer_info.district_province的set方法
     * 
     */
    public void setDistrictProvince(String districtProvince) {
        this.districtProvince = districtProvince == null ? null : districtProvince.trim();
    }

    /**
     * 数据字段 customer_info.district_city的get方法 
     * 
     */
    public String getDistrictCity() {
        return districtCity;
    }

    /**
     * 数据字段 customer_info.district_city的set方法
     * 
     */
    public void setDistrictCity(String districtCity) {
        this.districtCity = districtCity == null ? null : districtCity.trim();
    }

    /**
     * 数据字段 customer_info.district_county的get方法 
     * 
     */
    public String getDistrictCounty() {
        return districtCounty;
    }

    /**
     * 数据字段 customer_info.district_county的set方法
     * 
     */
    public void setDistrictCounty(String districtCounty) {
        this.districtCounty = districtCounty == null ? null : districtCounty.trim();
    }

    /**
     * 数据字段 customer_info.identity_detail的get方法 
     * 
     */
    public String getIdentityDetail() {
        return identityDetail;
    }

    /**
     * 数据字段 customer_info.identity_detail的set方法
     * 
     */
    public void setIdentityDetail(String identityDetail) {
        this.identityDetail = identityDetail == null ? null : identityDetail.trim();
    }

    /**
     * 数据字段 customer_info.contact_phone的get方法 
     * 
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * 数据字段 customer_info.contact_phone的set方法
     * 
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * 数据字段 customer_info.register_address_province的get方法 
     * 
     */
    public String getRegisterAddressProvince() {
        return registerAddressProvince;
    }

    /**
     * 数据字段 customer_info.register_address_province的set方法
     * 
     */
    public void setRegisterAddressProvince(String registerAddressProvince) {
        this.registerAddressProvince = registerAddressProvince == null ? null : registerAddressProvince.trim();
    }

    /**
     * 数据字段 customer_info.register_address_city的get方法 
     * 
     */
    public String getRegisterAddressCity() {
        return registerAddressCity;
    }

    /**
     * 数据字段 customer_info.register_address_city的set方法
     * 
     */
    public void setRegisterAddressCity(String registerAddressCity) {
        this.registerAddressCity = registerAddressCity == null ? null : registerAddressCity.trim();
    }

    /**
     * 数据字段 customer_info.register_address_country的get方法 
     * 
     */
    public String getRegisterAddressCountry() {
        return registerAddressCountry;
    }

    /**
     * 数据字段 customer_info.register_address_country的set方法
     * 
     */
    public void setRegisterAddressCountry(String registerAddressCountry) {
        this.registerAddressCountry = registerAddressCountry == null ? null : registerAddressCountry.trim();
    }

    /**
     * 数据字段 customer_info.register_address_detail的get方法 
     * 
     */
    public String getRegisterAddressDetail() {
        return registerAddressDetail;
    }

    /**
     * 数据字段 customer_info.register_address_detail的set方法
     * 
     */
    public void setRegisterAddressDetail(String registerAddressDetail) {
        this.registerAddressDetail = registerAddressDetail == null ? null : registerAddressDetail.trim();
    }

    /**
     * 数据字段 customer_info.live_address_province的get方法 
     * 
     */
    public String getLiveAddressProvince() {
        return liveAddressProvince;
    }

    /**
     * 数据字段 customer_info.live_address_province的set方法
     * 
     */
    public void setLiveAddressProvince(String liveAddressProvince) {
        this.liveAddressProvince = liveAddressProvince == null ? null : liveAddressProvince.trim();
    }

    /**
     * 数据字段 customer_info.live_address_city的get方法 
     * 
     */
    public String getLiveAddressCity() {
        return liveAddressCity;
    }

    /**
     * 数据字段 customer_info.live_address_city的set方法
     * 
     */
    public void setLiveAddressCity(String liveAddressCity) {
        this.liveAddressCity = liveAddressCity == null ? null : liveAddressCity.trim();
    }

    /**
     * 数据字段 customer_info.live_address_country的get方法 
     * 
     */
    public String getLiveAddressCountry() {
        return liveAddressCountry;
    }

    /**
     * 数据字段 customer_info.live_address_country的set方法
     * 
     */
    public void setLiveAddressCountry(String liveAddressCountry) {
        this.liveAddressCountry = liveAddressCountry == null ? null : liveAddressCountry.trim();
    }

    /**
     * 数据字段 customer_info.live_address_detail的get方法 
     * 
     */
    public String getLiveAddressDetail() {
        return liveAddressDetail;
    }

    /**
     * 数据字段 customer_info.live_address_detail的set方法
     * 
     */
    public void setLiveAddressDetail(String liveAddressDetail) {
        this.liveAddressDetail = liveAddressDetail == null ? null : liveAddressDetail.trim();
    }

    /**
     * 数据字段 customer_info.customer_grade的get方法 
     * 
     */
    public String getCustomerGrade() {
        return customerGrade;
    }

    /**
     * 数据字段 customer_info.customer_grade的set方法
     * 
     */
    public void setCustomerGrade(String customerGrade) {
        this.customerGrade = customerGrade == null ? null : customerGrade.trim();
    }

    /**
     * 数据字段 customer_info.financial_code的get方法 
     * 
     */
    public String getFinancialCode() {
        return financialCode;
    }

    /**
     * 数据字段 customer_info.financial_code的set方法
     * 
     */
    public void setFinancialCode(String financialCode) {
        this.financialCode = financialCode == null ? null : financialCode.trim();
    }

    /**
     * 数据字段 customer_info.first_contact_name的get方法 
     * 
     */
    public String getFirstContactName() {
        return firstContactName;
    }

    /**
     * 数据字段 customer_info.first_contact_name的set方法
     * 
     */
    public void setFirstContactName(String firstContactName) {
        this.firstContactName = firstContactName == null ? null : firstContactName.trim();
    }

    /**
     * 数据字段 customer_info.first_contact_phone的get方法 
     * 
     */
    public String getFirstContactPhone() {
        return firstContactPhone;
    }

    /**
     * 数据字段 customer_info.first_contact_phone的set方法
     * 
     */
    public void setFirstContactPhone(String firstContactPhone) {
        this.firstContactPhone = firstContactPhone == null ? null : firstContactPhone.trim();
    }

    /**
     * 数据字段 customer_info.customer_industry的get方法 
     * 
     */
    public String getCustomerIndustry() {
        return customerIndustry;
    }

    /**
     * 数据字段 customer_info.customer_industry的set方法
     * 
     */
    public void setCustomerIndustry(String customerIndustry) {
        this.customerIndustry = customerIndustry == null ? null : customerIndustry.trim();
    }

    /**
     * 数据字段 customer_info.frequent_customer的get方法 
     * 
     */
    public String getFrequentCustomer() {
        return frequentCustomer;
    }

    /**
     * 数据字段 customer_info.frequent_customer的set方法
     * 
     */
    public void setFrequentCustomer(String frequentCustomer) {
        this.frequentCustomer = frequentCustomer == null ? null : frequentCustomer.trim();
    }

    /**
     * 数据字段 customer_info.isBlack的get方法 
     * 
     */
    public Integer getIsblack() {
        return isblack;
    }

    /**
     * 数据字段 customer_info.isBlack的set方法
     * 
     */
    public void setIsblack(Integer isblack) {
        this.isblack = isblack;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}