package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MessageProcess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_process.id
     * 
     */
    private Long id;

    /**
     * 创建时间 -- message_process.create_time
     * 
     */
    private Date createTime;

    /**
     * 修改时间 -- message_process.update_time
     * 
     */
    private Date updateTime;

    /**
     * 提交人 -- message_process.creator
     * 
     */
    private Long creator;

    /**
     * 上传文件osskey -- message_process.osskey
     * 
     */
    private String osskey;

    /**
     * 短信内容 -- message_process.message
     * 
     */
    private String message;

    /**
     * 是否定时发送 -- message_process.is_timing
     * 
     */
    private Integer isTiming;

    /**
     * 发送原因 -- message_process.reason
     * 
     */
    private String reason;

    /**
     * 流程实例id -- message_process.process_instance_id
     * 
     */
    private String processInstanceId;

    /**
     * 状态 1-已发送 2-未发送 -- message_process.status
     * 
     */
    private Integer status;

    /**
     * 备注 -- message_process.memo
     * 
     */
    private String memo;

    /**
     * 发送时间 -- message_process.send_time
     * 
     */
    private Date sendTime;

    /**
     * 文件名 -- message_process.file_name
     * 
     */
    private String fileName;

    /**
     * message_process表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 message_process.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 message_process.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 message_process.create_time的get方法 
     * 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 message_process.create_time的set方法
     * 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 message_process.update_time的get方法 
     * 
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 message_process.update_time的set方法
     * 
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 message_process.creator的get方法 
     * 
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * 数据字段 message_process.creator的set方法
     * 
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * 数据字段 message_process.osskey的get方法 
     * 
     */
    public String getOsskey() {
        return osskey;
    }

    /**
     * 数据字段 message_process.osskey的set方法
     * 
     */
    public void setOsskey(String osskey) {
        this.osskey = osskey == null ? null : osskey.trim();
    }

    /**
     * 数据字段 message_process.message的get方法 
     * 
     */
    public String getMessage() {
        return message;
    }

    /**
     * 数据字段 message_process.message的set方法
     * 
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * 数据字段 message_process.is_timing的get方法 
     * 
     */
    public Integer getIsTiming() {
        return isTiming;
    }

    /**
     * 数据字段 message_process.is_timing的set方法
     * 
     */
    public void setIsTiming(Integer isTiming) {
        this.isTiming = isTiming;
    }

    /**
     * 数据字段 message_process.reason的get方法 
     * 
     */
    public String getReason() {
        return reason;
    }

    /**
     * 数据字段 message_process.reason的set方法
     * 
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * 数据字段 message_process.process_instance_id的get方法 
     * 
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * 数据字段 message_process.process_instance_id的set方法
     * 
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId == null ? null : processInstanceId.trim();
    }

    /**
     * 数据字段 message_process.status的get方法 
     * 
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 数据字段 message_process.status的set方法
     * 
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 数据字段 message_process.memo的get方法 
     * 
     */
    public String getMemo() {
        return memo;
    }

    /**
     * 数据字段 message_process.memo的set方法
     * 
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * 数据字段 message_process.send_time的get方法 
     * 
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * 数据字段 message_process.send_time的set方法
     * 
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * 数据字段 message_process.file_name的get方法 
     * 
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * 数据字段 message_process.file_name的set方法
     * 
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}