package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class Organization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     * 
     */
    private Long id;

    /**
     * 创建时间 -- organization.created_time
     * 
     */
    private Date createdTime;

    /**
     * 更新时间 -- organization.updated_time
     * 
     */
    private Date updatedTime;

    /**
     * 机构号 -- organization.org_no
     * 
     */
    private String orgNo;

    /**
     * 机构名 -- organization.org_name
     * 
     */
    private String orgName;

    /**
     * 上级机构id -- organization.upper_org_id
     * 
     */
    private Long upperOrgId;

    /**
     * 机构类型：来源于dic_item表 -- organization.org_type
     * 
     */
    private Long orgType;

    /**
     * 人行金融机构代码 -- organization.financial_institute_no
     * 
     */
    private String financialInstituteNo;

    /**
     * 金融机构许可证 -- organization.financial_institue_license
     * 
     */
    private String financialInstitueLicense;

    /**
     * 营业执照 -- organization.business_license
     * 
     */
    private String businessLicense;

    /**
     * 网点号 -- organization.branch_no
     * 
     */
    private String branchNo;

    /**
     * 交换号 -- organization.exchange_no
     * 
     */
    private String exchangeNo;

    /**
     * 机构管辖区 -- organization.org_jurisdiction
     * 
     */
    private String orgJurisdiction;

    /**
     * 机构地址 -- organization.org_address
     * 
     */
    private String orgAddress;

    /**
     * 机构邮编 -- organization.org_zip_code
     * 
     */
    private String orgZipCode;

    /**
     * 机构负责人 -- organization.org_principal
     * 
     */
    private String orgPrincipal;

    /**
     * 联系电话 -- organization.org_contact_phone
     * 
     */
    private String orgContactPhone;

    /**
     * 曾用名 -- organization.used_name
     * 
     */
    private String usedName;

    /**
     * 成立日期 -- organization.established_date
     * 
     */
    private Date establishedDate;

    /**
     * 机构状态

1：LOCKED 锁定
2: ACTIVE 正常
 来源于数据字典 -- organization.org_status
     * 
     */
    private Integer orgStatus;

    /**
     * 前端节点展开状态（针对有子节点的项，存open或closed） -- organization.state
     * 
     */
    private String state;

    /**
     * 状态设置时间 -- organization.status_time
     * 
     */
    private Date statusTime;

    /**
     * 管辖网点数 -- organization.branches_in_charge
     * 
     */
    private Integer branchesInCharge;

    /**
     * 客户经理数 -- organization.client_manager_no
     * 
     */
    private Integer clientManagerNo;

    /**
     * 备注 -- organization.memo
     * 
     */
    private String memo;

    /**
     * 是否启用，1：启用，0：禁用（此字段目前没用） -- organization.enable
     * 
     */
    private Integer enable;

    /**
     * 客商编码长度 -- organization.customer_code_len
     * 
     */
    private Integer customerCodeLen;

    /**
     * 机构属性  1-总公司 2-分公司  3-部门 -- organization.org_attribute
     * 
     */
    private Integer orgAttribute;

    /**
     * organization表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 organization.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 organization.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 organization.created_time的get方法 
     * 
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 数据字段 organization.created_time的set方法
     * 
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 数据字段 organization.updated_time的get方法 
     * 
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 数据字段 organization.updated_time的set方法
     * 
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * 数据字段 organization.org_no的get方法 
     * 
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * 数据字段 organization.org_no的set方法
     * 
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * 数据字段 organization.org_name的get方法 
     * 
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * 数据字段 organization.org_name的set方法
     * 
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * 数据字段 organization.upper_org_id的get方法 
     * 
     */
    public Long getUpperOrgId() {
        return upperOrgId;
    }

    /**
     * 数据字段 organization.upper_org_id的set方法
     * 
     */
    public void setUpperOrgId(Long upperOrgId) {
        this.upperOrgId = upperOrgId;
    }

    /**
     * 数据字段 organization.org_type的get方法 
     * 
     */
    public Long getOrgType() {
        return orgType;
    }

    /**
     * 数据字段 organization.org_type的set方法
     * 
     */
    public void setOrgType(Long orgType) {
        this.orgType = orgType;
    }

    /**
     * 数据字段 organization.financial_institute_no的get方法 
     * 
     */
    public String getFinancialInstituteNo() {
        return financialInstituteNo;
    }

    /**
     * 数据字段 organization.financial_institute_no的set方法
     * 
     */
    public void setFinancialInstituteNo(String financialInstituteNo) {
        this.financialInstituteNo = financialInstituteNo == null ? null : financialInstituteNo.trim();
    }

    /**
     * 数据字段 organization.financial_institue_license的get方法 
     * 
     */
    public String getFinancialInstitueLicense() {
        return financialInstitueLicense;
    }

    /**
     * 数据字段 organization.financial_institue_license的set方法
     * 
     */
    public void setFinancialInstitueLicense(String financialInstitueLicense) {
        this.financialInstitueLicense = financialInstitueLicense == null ? null : financialInstitueLicense.trim();
    }

    /**
     * 数据字段 organization.business_license的get方法 
     * 
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * 数据字段 organization.business_license的set方法
     * 
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * 数据字段 organization.branch_no的get方法 
     * 
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * 数据字段 organization.branch_no的set方法
     * 
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * 数据字段 organization.exchange_no的get方法 
     * 
     */
    public String getExchangeNo() {
        return exchangeNo;
    }

    /**
     * 数据字段 organization.exchange_no的set方法
     * 
     */
    public void setExchangeNo(String exchangeNo) {
        this.exchangeNo = exchangeNo == null ? null : exchangeNo.trim();
    }

    /**
     * 数据字段 organization.org_jurisdiction的get方法 
     * 
     */
    public String getOrgJurisdiction() {
        return orgJurisdiction;
    }

    /**
     * 数据字段 organization.org_jurisdiction的set方法
     * 
     */
    public void setOrgJurisdiction(String orgJurisdiction) {
        this.orgJurisdiction = orgJurisdiction == null ? null : orgJurisdiction.trim();
    }

    /**
     * 数据字段 organization.org_address的get方法 
     * 
     */
    public String getOrgAddress() {
        return orgAddress;
    }

    /**
     * 数据字段 organization.org_address的set方法
     * 
     */
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress == null ? null : orgAddress.trim();
    }

    /**
     * 数据字段 organization.org_zip_code的get方法 
     * 
     */
    public String getOrgZipCode() {
        return orgZipCode;
    }

    /**
     * 数据字段 organization.org_zip_code的set方法
     * 
     */
    public void setOrgZipCode(String orgZipCode) {
        this.orgZipCode = orgZipCode == null ? null : orgZipCode.trim();
    }

    /**
     * 数据字段 organization.org_principal的get方法 
     * 
     */
    public String getOrgPrincipal() {
        return orgPrincipal;
    }

    /**
     * 数据字段 organization.org_principal的set方法
     * 
     */
    public void setOrgPrincipal(String orgPrincipal) {
        this.orgPrincipal = orgPrincipal == null ? null : orgPrincipal.trim();
    }

    /**
     * 数据字段 organization.org_contact_phone的get方法 
     * 
     */
    public String getOrgContactPhone() {
        return orgContactPhone;
    }

    /**
     * 数据字段 organization.org_contact_phone的set方法
     * 
     */
    public void setOrgContactPhone(String orgContactPhone) {
        this.orgContactPhone = orgContactPhone == null ? null : orgContactPhone.trim();
    }

    /**
     * 数据字段 organization.used_name的get方法 
     * 
     */
    public String getUsedName() {
        return usedName;
    }

    /**
     * 数据字段 organization.used_name的set方法
     * 
     */
    public void setUsedName(String usedName) {
        this.usedName = usedName == null ? null : usedName.trim();
    }

    /**
     * 数据字段 organization.established_date的get方法 
     * 
     */
    public Date getEstablishedDate() {
        return establishedDate;
    }

    /**
     * 数据字段 organization.established_date的set方法
     * 
     */
    public void setEstablishedDate(Date establishedDate) {
        this.establishedDate = establishedDate;
    }

    /**
     * 数据字段 organization.org_status的get方法 
     * 
     */
    public Integer getOrgStatus() {
        return orgStatus;
    }

    /**
     * 数据字段 organization.org_status的set方法
     * 
     */
    public void setOrgStatus(Integer orgStatus) {
        this.orgStatus = orgStatus;
    }

    /**
     * 数据字段 organization.state的get方法 
     * 
     */
    public String getState() {
        return state;
    }

    /**
     * 数据字段 organization.state的set方法
     * 
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * 数据字段 organization.status_time的get方法 
     * 
     */
    public Date getStatusTime() {
        return statusTime;
    }

    /**
     * 数据字段 organization.status_time的set方法
     * 
     */
    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    /**
     * 数据字段 organization.branches_in_charge的get方法 
     * 
     */
    public Integer getBranchesInCharge() {
        return branchesInCharge;
    }

    /**
     * 数据字段 organization.branches_in_charge的set方法
     * 
     */
    public void setBranchesInCharge(Integer branchesInCharge) {
        this.branchesInCharge = branchesInCharge;
    }

    /**
     * 数据字段 organization.client_manager_no的get方法 
     * 
     */
    public Integer getClientManagerNo() {
        return clientManagerNo;
    }

    /**
     * 数据字段 organization.client_manager_no的set方法
     * 
     */
    public void setClientManagerNo(Integer clientManagerNo) {
        this.clientManagerNo = clientManagerNo;
    }

    /**
     * 数据字段 organization.memo的get方法 
     * 
     */
    public String getMemo() {
        return memo;
    }

    /**
     * 数据字段 organization.memo的set方法
     * 
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * 数据字段 organization.enable的get方法 
     * 
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * 数据字段 organization.enable的set方法
     * 
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * 数据字段 organization.customer_code_len的get方法 
     * 
     */
    public Integer getCustomerCodeLen() {
        return customerCodeLen;
    }

    /**
     * 数据字段 organization.customer_code_len的set方法
     * 
     */
    public void setCustomerCodeLen(Integer customerCodeLen) {
        this.customerCodeLen = customerCodeLen;
    }

    /**
     * 数据字段 organization.org_attribute的get方法 
     * 
     */
    public Integer getOrgAttribute() {
        return orgAttribute;
    }

    /**
     * 数据字段 organization.org_attribute的set方法
     * 
     */
    public void setOrgAttribute(Integer orgAttribute) {
        this.orgAttribute = orgAttribute;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}