package com.zlkcxd.dao.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class WorkflowGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_group.id
     * 
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_group.created_time
     * 
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_group.updated_time
     * 
     */
    private Date updatedTime;

    /**
     * 组名 -- workflow_group.name
     * 
     */
    private String name;

    /**
     * 1-停用、2-启用 -- workflow_group.enable
     * 
     */
    private Integer enable;

    /**
     * 是否全部人审批 1-是、2-否 -- workflow_group.status
     * 
     */
    private Integer status;

    /**
     * 审批组 -- workflow_group.approve_group
     * 
     */
    private String approveGroup;

    /**
     * 用户账号 -- workflow_group.approve_user
     * 
     */
    private String approveUser;

    /**
     * 产品id -- workflow_group.product_id
     * 
     */
    private Long productId;

    /**
     * workflow_group表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 workflow_group.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 workflow_group.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 workflow_group.created_time的get方法 
     * 
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 数据字段 workflow_group.created_time的set方法
     * 
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 数据字段 workflow_group.updated_time的get方法 
     * 
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 数据字段 workflow_group.updated_time的set方法
     * 
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * 数据字段 workflow_group.name的get方法 
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * 数据字段 workflow_group.name的set方法
     * 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 数据字段 workflow_group.enable的get方法 
     * 
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * 数据字段 workflow_group.enable的set方法
     * 
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * 数据字段 workflow_group.status的get方法 
     * 
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 数据字段 workflow_group.status的set方法
     * 
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 数据字段 workflow_group.approve_group的get方法 
     * 
     */
    public String getApproveGroup() {
        return approveGroup;
    }

    /**
     * 数据字段 workflow_group.approve_group的set方法
     * 
     */
    public void setApproveGroup(String approveGroup) {
        this.approveGroup = approveGroup == null ? null : approveGroup.trim();
    }

    /**
     * 数据字段 workflow_group.approve_user的get方法 
     * 
     */
    public String getApproveUser() {
        return approveUser;
    }

    /**
     * 数据字段 workflow_group.approve_user的set方法
     * 
     */
    public void setApproveUser(String approveUser) {
        this.approveUser = approveUser == null ? null : approveUser.trim();
    }

    /**
     * 数据字段 workflow_group.product_id的get方法 
     * 
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * 数据字段 workflow_group.product_id的set方法
     * 
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}