package com.zlkcxd.capital.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class InvestProject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_project.id
     * 
     */
    private Long id;

    /**
     * 记录逻辑删除标记（1：正常、0：删除） -- invest_project.is_delete
     * 
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_project.create_time
     * 
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_project.update_time
     * 
     */
    private Date updateTime;

    /**
     * 项目名称 -- invest_project.project_name
     * 
     */
    private String projectName;

    /**
     * 投资方项目ID（关联投资方项目表） -- invest_project.invest_project_id
     * 
     */
    private Long investProjectId;

    /**
     * 投资类型（1：股权投资、2：债权投资） -- invest_project.invest_type
     * 
     */
    private Integer investType;

    /**
     * 项目类型（1：长期、2：短期） -- invest_project.project_type
     * 
     */
    private Integer projectType;

    /**
     * 项目金额 -- invest_project.project_amount
     * 
     */
    private BigDecimal projectAmount;

    /**
     * 项目收益率（%） -- invest_project.project_profit_tate
     * 
     */
    private BigDecimal projectProfitTate;

    /**
     * 公司投资金额 -- invest_project.company_invest_amount
     * 
     */
    private BigDecimal companyInvestAmount;

    /**
     * 募集资金限额 -- invest_project.raise_capital_limit
     * 
     */
    private BigDecimal raiseCapitalLimit;

    /**
     * 项目起始日 -- invest_project.project_start_date
     * 
     */
    private Date projectStartDate;

    /**
     * 项目结束日 -- invest_project.project_end_date
     * 
     */
    private Date projectEndDate;

    /**
     * 项目天数（由项目结束日-项目起始日） -- invest_project.project_days
     * 
     */
    private Integer projectDays;

    /**
     * 集合成立日 -- invest_project.raise_date
     * 
     */
    private Date raiseDate;

    /**
     * 对外投资日 -- invest_project.Invest_day
     * 
     */
    private Date investDay;

    /**
     * 当年开放日 -- invest_project.year_open_date
     * 
     */
    private Date yearOpenDate;

    /**
     * 项目阶段（1：募集中、2：投资中、3：开放期, 4: 项目结束） -- invest_project.project_stage
     * 
     */
    private Integer projectStage;

    /**
     * 开放期次数 -- invest_project.open_times
     * 
     */
    private Integer openTimes;

    /**
     * 是否开放期募集 -- invest_project.is_open_raise
     * 
     */
    private Integer isOpenRaise;

    /**
     * 项目描述 -- invest_project.project_describe
     * 
     */
    private String projectDescribe;

    /**
     * 项目余额 -- invest_project.project_balance
     * 
     */
    private BigDecimal projectBalance;

    /**
     * 项目结算状态 0:未结算  1:已结算 -- invest_project.settlement_status
     * 
     */
    private Integer settlementStatus;

    /**
     * 操作人 -- invest_project.user_id
     * 
     */
    private Long userId;

    /**
     * 流程实例id -- invest_project.approval_process_id
     * 
     */
    private String approvalProcessId;

    /**
     * invest_project表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 invest_project.id的get方法 
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 invest_project.id的set方法
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 invest_project.is_delete的get方法 
     * 
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * 数据字段 invest_project.is_delete的set方法
     * 
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * 数据字段 invest_project.create_time的get方法 
     * 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 invest_project.create_time的set方法
     * 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 invest_project.update_time的get方法 
     * 
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 invest_project.update_time的set方法
     * 
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 invest_project.project_name的get方法 
     * 
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * 数据字段 invest_project.project_name的set方法
     * 
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * 数据字段 invest_project.invest_project_id的get方法 
     * 
     */
    public Long getInvestProjectId() {
        return investProjectId;
    }

    /**
     * 数据字段 invest_project.invest_project_id的set方法
     * 
     */
    public void setInvestProjectId(Long investProjectId) {
        this.investProjectId = investProjectId;
    }

    /**
     * 数据字段 invest_project.invest_type的get方法 
     * 
     */
    public Integer getInvestType() {
        return investType;
    }

    /**
     * 数据字段 invest_project.invest_type的set方法
     * 
     */
    public void setInvestType(Integer investType) {
        this.investType = investType;
    }

    /**
     * 数据字段 invest_project.project_type的get方法 
     * 
     */
    public Integer getProjectType() {
        return projectType;
    }

    /**
     * 数据字段 invest_project.project_type的set方法
     * 
     */
    public void setProjectType(Integer projectType) {
        this.projectType = projectType;
    }

    /**
     * 数据字段 invest_project.project_amount的get方法 
     * 
     */
    public BigDecimal getProjectAmount() {
        return projectAmount;
    }

    /**
     * 数据字段 invest_project.project_amount的set方法
     * 
     */
    public void setProjectAmount(BigDecimal projectAmount) {
        this.projectAmount = projectAmount;
    }

    /**
     * 数据字段 invest_project.project_profit_tate的get方法 
     * 
     */
    public BigDecimal getProjectProfitTate() {
        return projectProfitTate;
    }

    /**
     * 数据字段 invest_project.project_profit_tate的set方法
     * 
     */
    public void setProjectProfitTate(BigDecimal projectProfitTate) {
        this.projectProfitTate = projectProfitTate;
    }

    /**
     * 数据字段 invest_project.company_invest_amount的get方法 
     * 
     */
    public BigDecimal getCompanyInvestAmount() {
        return companyInvestAmount;
    }

    /**
     * 数据字段 invest_project.company_invest_amount的set方法
     * 
     */
    public void setCompanyInvestAmount(BigDecimal companyInvestAmount) {
        this.companyInvestAmount = companyInvestAmount;
    }

    /**
     * 数据字段 invest_project.raise_capital_limit的get方法 
     * 
     */
    public BigDecimal getRaiseCapitalLimit() {
        return raiseCapitalLimit;
    }

    /**
     * 数据字段 invest_project.raise_capital_limit的set方法
     * 
     */
    public void setRaiseCapitalLimit(BigDecimal raiseCapitalLimit) {
        this.raiseCapitalLimit = raiseCapitalLimit;
    }

    /**
     * 数据字段 invest_project.project_start_date的get方法 
     * 
     */
    public Date getProjectStartDate() {
        return projectStartDate;
    }

    /**
     * 数据字段 invest_project.project_start_date的set方法
     * 
     */
    public void setProjectStartDate(Date projectStartDate) {
        this.projectStartDate = projectStartDate;
    }

    /**
     * 数据字段 invest_project.project_end_date的get方法 
     * 
     */
    public Date getProjectEndDate() {
        return projectEndDate;
    }

    /**
     * 数据字段 invest_project.project_end_date的set方法
     * 
     */
    public void setProjectEndDate(Date projectEndDate) {
        this.projectEndDate = projectEndDate;
    }

    /**
     * 数据字段 invest_project.project_days的get方法 
     * 
     */
    public Integer getProjectDays() {
        return projectDays;
    }

    /**
     * 数据字段 invest_project.project_days的set方法
     * 
     */
    public void setProjectDays(Integer projectDays) {
        this.projectDays = projectDays;
    }

    /**
     * 数据字段 invest_project.raise_date的get方法 
     * 
     */
    public Date getRaiseDate() {
        return raiseDate;
    }

    /**
     * 数据字段 invest_project.raise_date的set方法
     * 
     */
    public void setRaiseDate(Date raiseDate) {
        this.raiseDate = raiseDate;
    }

    /**
     * 数据字段 invest_project.Invest_day的get方法 
     * 
     */
    public Date getInvestDay() {
        return investDay;
    }

    /**
     * 数据字段 invest_project.Invest_day的set方法
     * 
     */
    public void setInvestDay(Date investDay) {
        this.investDay = investDay;
    }

    /**
     * 数据字段 invest_project.year_open_date的get方法 
     * 
     */
    public Date getYearOpenDate() {
        return yearOpenDate;
    }

    /**
     * 数据字段 invest_project.year_open_date的set方法
     * 
     */
    public void setYearOpenDate(Date yearOpenDate) {
        this.yearOpenDate = yearOpenDate;
    }

    /**
     * 数据字段 invest_project.project_stage的get方法 
     * 
     */
    public Integer getProjectStage() {
        return projectStage;
    }

    /**
     * 数据字段 invest_project.project_stage的set方法
     * 
     */
    public void setProjectStage(Integer projectStage) {
        this.projectStage = projectStage;
    }

    /**
     * 数据字段 invest_project.open_times的get方法 
     * 
     */
    public Integer getOpenTimes() {
        return openTimes;
    }

    /**
     * 数据字段 invest_project.open_times的set方法
     * 
     */
    public void setOpenTimes(Integer openTimes) {
        this.openTimes = openTimes;
    }

    /**
     * 数据字段 invest_project.is_open_raise的get方法 
     * 
     */
    public Integer getIsOpenRaise() {
        return isOpenRaise;
    }

    /**
     * 数据字段 invest_project.is_open_raise的set方法
     * 
     */
    public void setIsOpenRaise(Integer isOpenRaise) {
        this.isOpenRaise = isOpenRaise;
    }

    /**
     * 数据字段 invest_project.project_describe的get方法 
     * 
     */
    public String getProjectDescribe() {
        return projectDescribe;
    }

    /**
     * 数据字段 invest_project.project_describe的set方法
     * 
     */
    public void setProjectDescribe(String projectDescribe) {
        this.projectDescribe = projectDescribe == null ? null : projectDescribe.trim();
    }

    /**
     * 数据字段 invest_project.project_balance的get方法 
     * 
     */
    public BigDecimal getProjectBalance() {
        return projectBalance;
    }

    /**
     * 数据字段 invest_project.project_balance的set方法
     * 
     */
    public void setProjectBalance(BigDecimal projectBalance) {
        this.projectBalance = projectBalance;
    }

    /**
     * 数据字段 invest_project.settlement_status的get方法 
     * 
     */
    public Integer getSettlementStatus() {
        return settlementStatus;
    }

    /**
     * 数据字段 invest_project.settlement_status的set方法
     * 
     */
    public void setSettlementStatus(Integer settlementStatus) {
        this.settlementStatus = settlementStatus;
    }

    /**
     * 数据字段 invest_project.user_id的get方法 
     * 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 数据字段 invest_project.user_id的set方法
     * 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 数据字段 invest_project.approval_process_id的get方法 
     * 
     */
    public String getApprovalProcessId() {
        return approvalProcessId;
    }

    /**
     * 数据字段 invest_project.approval_process_id的set方法
     * 
     */
    public void setApprovalProcessId(String approvalProcessId) {
        this.approvalProcessId = approvalProcessId == null ? null : approvalProcessId.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}